# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: cloudnative-pg
      image: ghcr.io/bitmoa/cloudnative-pg:1.27.0-debian-12-r1
    - name: plugin-barman-cloud
      image: ghcr.io/bitmoa/plugin-barman-cloud:0.6.0-debian-12-r0
    - name: plugin-barman-cloud-sidecar
      image: ghcr.io/bitmoa/plugin-barman-cloud-sidecar:0.6.0-debian-12-r0
    - name: postgresql
      image: ghcr.io/bitmoa/postgresql:17.6.0-debian-12-r4
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 1.27.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitmoacharts
  tags:
  - bitmoa-common
  version: 2.x.x
description: CloudNativePG is an open-source tool for managing PostgreSQL databases
  on Kubernetes, from setup to ongoing upkeep.
home: https://bitmoa.net
icon: https://bitmoa.net/assets/stacks/cloudnative-pg/img/cloudnative-pg-stack-220x234.png
keywords:
- cloudnative-pg
- operator
- postgresql
maintainers:
- name: Bitmoa
  url: https://github.com/bitmoa/charts
name: cloudnative-pg
sources:
- https://github.com/bitmoa/charts/tree/main/bitmoa/cloudnative-pg
version: 1.0.12
